FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge

# Install dependencies
RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        libdrm-dev:arm64 \
        pkg-config

# Copy librga library to the image
COPY libs/Linux/gcc-aarch64/librga.so /usr/lib/aarch64-linux-gnu/
COPY libs/Linux/gcc-aarch64/librga.a /usr/lib/aarch64-linux-gnu/
COPY include/ /usr/local/include/rga/

# Update library cache
RUN ldconfig

WORKDIR /project
