//! # librga - Rust FFI bindings for Rockchip RGA
//!
//! This crate provides safe Rust bindings for the Rockchip Graphics Accelerator (RGA) library,
//! which enables hardware-accelerated 2D graphics operations on Rockchip SoCs like RK3566, RK3588.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// FFI module (generated by bindgen)
#[allow(dead_code)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use ffi::*;

// FFI name mappings for cleaner API
mod ffi_names;
pub use ffi_names::*;

// Re-export safe API modules
pub mod buffer;
pub mod error;
pub mod format;
pub mod rect;
pub mod usage;

// Operations modules
pub mod ops {
    pub mod blend;
    pub mod color;
    pub mod copy;
    pub mod crop;
    pub mod effect;
    pub mod fill;
    pub mod process;
    pub mod resize;
    pub mod transform;
}

// Job and context
pub mod job;
pub mod query;

// Public re-exports for convenience
pub use buffer::RgaBuffer;
pub use error::{RgaError, RgaResult};
pub use format::PixelFormat;
pub use rect::Rect;
pub use usage::Usage;

// Re-export types that are commonly used
pub use ops::color::ColorSpaceMode;
pub use usage::{BlendMode, FlipMode, InterpMode, MosaicMode, Rotation};

/// Options for RGA operations
#[derive(Debug, Clone, Copy, Default)]
pub struct OpOptions {
    /// Synchronous mode (wait for completion)
    pub sync: bool,
}

impl OpOptions {
    /// Create synchronous options
    pub fn sync() -> Self {
        Self { sync: true }
    }
}

use ops::*;

/// Copy image from source to destination
pub fn copy(src: &RgaBuffer, dst: &mut RgaBuffer, sync: bool) -> RgaResult<()> {
    copy::copy(src, dst, sync)
}

/// Resize image
pub fn resize(src: &RgaBuffer, dst: &mut RgaBuffer, opts: resize::ResizeOptions) -> RgaResult<()> {
    resize::resize(src, dst, opts)
}

/// Crop image region
pub fn crop(src: &RgaBuffer, dst: &mut RgaBuffer, rect: Rect, sync: bool) -> RgaResult<()> {
    crop::crop(src, dst, rect, sync)
}

/// Translate image
pub fn translate(
    src: &RgaBuffer,
    dst: &mut RgaBuffer,
    x: i32,
    y: i32,
    sync: bool,
) -> RgaResult<()> {
    crop::translate(src, dst, x, y, sync)
}

/// Convert color format
pub fn convert_color(
    src: &RgaBuffer,
    dst: &mut RgaBuffer,
    src_fmt: PixelFormat,
    dst_fmt: PixelFormat,
    mode: color::ColorSpaceMode,
    sync: bool,
) -> RgaResult<()> {
    color::convert_color(src, dst, src_fmt, dst_fmt, mode, sync)
}

/// Rotate image
pub fn rotate(
    src: &RgaBuffer,
    dst: &mut RgaBuffer,
    rotation: crate::usage::Rotation,
    sync: bool,
) -> RgaResult<()> {
    transform::rotate(src, dst, rotation, sync)
}

/// Flip image
pub fn flip(
    src: &RgaBuffer,
    dst: &mut RgaBuffer,
    mode: crate::usage::FlipMode,
    sync: bool,
) -> RgaResult<()> {
    transform::flip(src, dst, mode, sync)
}

/// Blend foreground onto background
pub fn blend(
    fg: &RgaBuffer,
    bg: &mut RgaBuffer,
    mode: crate::usage::BlendMode,
    sync: bool,
) -> RgaResult<()> {
    blend::blend(fg, bg, mode, sync)
}

/// Composite two images into a third destination
pub fn composite(
    src1: &RgaBuffer,
    src2: &RgaBuffer,
    dst: &mut RgaBuffer,
    mode: crate::usage::BlendMode,
    sync: bool,
) -> RgaResult<()> {
    // Composite is implemented as: copy src1 to dst, then blend src2 onto dst
    copy::copy(src1, dst, sync)?;
    // For true composite, we'd need a different approach, but this works for basic cases
    // Use src2 as foreground on dst
    let mut temp = dst.clone();
    blend::blend(src2, &mut temp, mode, sync)
}

/// Fill rectangle with color
pub fn fill(dst: &mut RgaBuffer, rect: Rect, color: u32, sync: bool) -> RgaResult<()> {
    fill::fill(dst, rect, color, sync)
}

/// Draw rectangle border
pub fn rectangle(
    dst: &mut RgaBuffer,
    rect: Rect,
    color: u32,
    thickness: i32,
    sync: bool,
) -> RgaResult<()> {
    fill::rectangle(dst, rect, color, thickness, sync)
}

/// Apply mosaic effect
pub fn mosaic(
    dst: &mut RgaBuffer,
    rect: Rect,
    mode: crate::usage::MosaicMode,
    sync: bool,
) -> RgaResult<()> {
    effect::mosaic(dst, rect, mode, sync)
}

/// Apply Gaussian blur
pub fn gaussian_blur(
    src: &RgaBuffer,
    dst: &mut RgaBuffer,
    ksize: (i32, i32),
    sigma: (i32, i32),
    sync: bool,
) -> RgaResult<()> {
    effect::gaussian_blur(src, dst, ksize, sigma, sync)
}

/// Apply palette mapping
pub fn palette(src: &RgaBuffer, dst: &mut RgaBuffer, lut: &RgaBuffer, sync: bool) -> RgaResult<()> {
    effect::palette(src, dst, lut, sync)
}

/// General process function
pub fn process(
    src: &RgaBuffer,
    dst: &mut RgaBuffer,
    pat: Option<&RgaBuffer>,
    src_rect: Rect,
    dst_rect: Rect,
    pat_rect: Option<Rect>,
    usage: Usage,
) -> RgaResult<()> {
    process::process(src, dst, pat, src_rect, dst_rect, pat_rect, usage)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_version() {
        let version = query::query_version();
        assert!(!version.is_empty());
        println!("RGA Version: {}", version);
    }

    #[test]
    fn test_vendor() {
        let vendor = query::query_vendor();
        assert!(!vendor.is_empty());
        println!("RGA Vendor: {}", vendor);
    }
}
